import { vi } from 'vitest';

export const Controller = vi.fn();
export const Model = vi.fn();
export const View = vi.fn();
export const Utils = {
    debug: 0,
    console: {
        debug: vi.fn(),
        log: vi.fn(),
        warn: vi.fn(),
        error: vi.fn(),
    },
    localStorage: {
        getItem: vi.fn(),
        setItem: vi.fn(),
        key: vi.fn(),
        length: 0,
        removeItem: vi.fn(),
    },
    loadScript: vi.fn(),
    isCustomError: vi.fn(),
    composeError: vi.fn(),
    stringTrimEnd: vi.fn(),
    stringCapitalize: vi.fn(),
    string2Uint8Array: vi.fn(),
    atob: vi.fn(),
    btoa: vi.fn(),
};
export const ModelPropID = {
    database: "database",
    example: "example",
    arrayBounds: "arrayBounds",
    implicitLines: "implicitLines",
    integerOverflow: "integerOverflow",
    trace: "trace",
    speed: "speed",
    sound: "sound",
    showKbd: "showKbd",
    showCpc: "showCpc",
    dragElements: "dragElements",
    basicVersion: "basicVersion",
    palette: "palette",
    bench: "bench",
    processFileImports: "processFileImports",
    prettyLowercaseVars: "prettyLowercaseVars",
    selectDataFiles: "selectDataFiles",
    exampleIndex: "exampleIndex",
    autorun: "autorun",
    linesOnLoad: "linesOnLoad",
};
export const ViewID = {
    mainArea: "mainArea",
    cpcArea: "cpcArea",
    cpcCanvas: "cpcCanvas",
    textText: "textText",
    noCanvas: "noCanvas",
    kbdArea: "kbdArea",
    kbdAreaInner: "kbdAreaInner",
    kbdAlpha: "kbdAlpha",
    kbdNum: "kbdNum",
    outputArea: "outputArea",
    consoleLogText: "consoleLogText",
    inputText: "inputText",
    statusText: "statusText",
    runButton: "runButton",
    dropZone: "dropZone",
    fileInput: "fileInput",
    databaseSelect: "databaseSelect",
    directorySelect: "directorySelect",
    exampleSelect: "exampleSelect",
    resultText: "resultText",
    varSelect: "varSelect",
    varText: "varText",
    renumNewInput: "renumNewInput",
    renumStartInput: "renumStartInput",
    renumStepInput: "renumStepInput",
    renumKeepInput: "renumKeepInput",
    inp2Text: "inp2Text",
    disassText: "disassText",
    undoButton: "undoButton",
    undoButton2: "undoButton2",
    redoButton: "redoButton",
    redoButton2: "redoButton2",
    stopButton: "stopButton",
    continueButton: "continueButton",
    resetButton: "resetButton",
    parseRunButton: "parseRunButton",
    prettySpaceInput: "prettySpaceInput",
    prettyBracketsInput: "prettyBracketsInput",
    prettyColonsInput: "prettyColonsInput",
    inputArea: "inputArea",
    consoleLogArea: "consoleLogArea",
    disassArea: "disassArea",
    inp2Area: "inp2Area",
    resultArea: "resultArea",
    variableArea: "variableArea",
    window: "window",
    exportFileSelect: "exportFileSelect",
    exportTokenizedInput: "exportTokenizedInput",
    exportDSKInput: "exportDSKInput",
    exportDSKFormatSelect: "exportDSKFormatSelect",
    exportDSKStripEmptyInput: "exportDSKStripEmptyInput",
    exportBase64Input: "exportBase64Input",
    galleryAreaItems: "galleryAreaItems"
};
export const Polyfills = vi.fn();
export const FileHandler = {
    joinMeta: vi.fn()
};
export const DiskImage = {
    getFilenameAndExtension: vi.fn(),
    createAmsdosHeader: vi.fn(),
    combineAmsdosHeader: vi.fn()
};
